# Generated by Django 4.1.6 on 2023-04-18 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiempoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.IntegerField(blank=True, null=True)),
                ('minutos', models.IntegerField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('control_extra', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField()),
                ('consola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementime.consola')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_control', models.IntegerField(default=0)),
                ('costo_tiempo', models.IntegerField(default=0)),
                ('costo_total', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_juego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementime.tiempojuego')),
            ],
        ),
    ]
