# Generated by Django 4.1.6 on 2023-05-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('extra_controller', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField()),
                ('console', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementime.console')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_cost', models.IntegerField(default=0)),
                ('time_cost', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('game_time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementime.gametime')),
            ],
        ),
    ]
