# Generated by Django 4.1.6 on 2023-02-25 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiempoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.IntegerField(default=0)),
                ('minutos', models.IntegerField(default=0)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('control_extra', models.IntegerField(default=0)),
                ('costo_control', models.IntegerField(default=0)),
                ('costo_tiempo', models.IntegerField(default=0)),
                ('costo_total', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementime.consola')),
            ],
        ),
        migrations.CreateModel(
            name='TiempoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_extra', models.IntegerField()),
                ('minutos_extra', models.IntegerField()),
                ('costo_tiempo_extra', models.CharField(max_length=50)),
                ('is_completed', models.BooleanField()),
                ('tiempo_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementime.tiempojuego')),
            ],
        ),
    ]
