# Generated by Django 4.1.6 on 2023-03-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0002_alter_tiempojuego_hora_fin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TiempoExtra',
        ),
    ]
