# Generated by Django 4.1.6 on 2023-03-01 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0003_delete_tiempoextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempojuego',
            name='costo_control',
        ),
        migrations.RemoveField(
            model_name='tiempojuego',
            name='costo_tiempo',
        ),
        migrations.RemoveField(
            model_name='tiempojuego',
            name='costo_total',
        ),
        migrations.RemoveField(
            model_name='tiempojuego',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='consola',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tiempojuego',
            name='control_extra',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tiempojuego',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tiempojuego',
            name='horas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tiempojuego',
            name='minutos',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_control', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo_tiempo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_juego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementime.tiempojuego')),
            ],
        ),
    ]
