# Generated by Django 4.1.6 on 2023-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0004_remove_tiempojuego_costo_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempojuego',
            name='control_extra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tiempojuego',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tiempojuego',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
