# Generated by Django 4.1.6 on 2023-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0005_alter_tiempojuego_control_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempojuego',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
