# Generated by Django 4.1.6 on 2023-03-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0006_tiempojuego_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='costo_control',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='precio',
            name='costo_tiempo',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='precio',
            name='costo_total',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tiempojuego',
            name='control_extra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiempojuego',
            name='hora_fin',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiempojuego',
            name='horas',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiempojuego',
            name='minutos',
            field=models.IntegerField(blank=True),
        ),
    ]
