# Generated by Django 4.1.6 on 2023-03-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0007_alter_precio_costo_control_alter_precio_costo_tiempo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempojuego',
            name='horas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
