# Generated by Django 4.1.6 on 2023-03-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0008_alter_tiempojuego_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempojuego',
            name='minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
