# Generated by Django 4.1.6 on 2023-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0009_alter_tiempojuego_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempojuego',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
