# Generated by Django 4.1.6 on 2023-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0010_alter_tiempojuego_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempojuego',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
