# Generated by Django 4.1.6 on 2023-03-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0011_alter_tiempojuego_hora_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempojuego',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
