# Generated by Django 4.1.6 on 2023-03-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0014_alter_tiempojuego_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='costo_control',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='precio',
            name='costo_tiempo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='precio',
            name='costo_total',
            field=models.IntegerField(default=0),
        ),
    ]
