# Generated by Django 4.1.6 on 2023-03-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0015_alter_precio_costo_control_alter_precio_costo_tiempo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempojuego',
            name='consola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managementime.consola'),
        ),
    ]
