# Generated by Django 4.1.6 on 2023-03-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementime', '0016_alter_tiempojuego_consola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempojuego',
            name='consola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementime.consola'),
        ),
    ]
